### ISSUE TITLE
Building the project ("Error in word1 %in% stop_words$word : object 'word1' not found")

### ISSUE THREAD

**Issue by vrrdnt** [BorisNikulin/discord-chat-analysis#8]
Hello!

Using RStudio, I followed the steps in #3, but when I Knit the README.Rmd file, I seem to be getting stuck at an error that occurs during the Bigram tokenization section.

The full output:
```
Quitting from lines 117-126 (README.Rmd) 
Error in word1 %in% stop_words$word : object 'word1' not found
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> %>% -> %in%
In addition: Warning messages:
1: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
This warning is displayed once per session. 
2: In remove && !as.character(col) %in% into :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
Execution halted
```

If you need any more info, please let me know!

**Comment by BorisNikulin** [comment]
I reran this project in my new WSL environment and there where no errors...
> Works on my machine

Here is how I built the project from scratch.

```bash
# install R
# install R's pip, packrat, globally with sudo
$ sudo -i R
> install.packages('packrat')
> q()
# no need to save workspace
# install tool to create markdown docs used by knitr
$ sudo apt install pandoc
$ git clone <this>
$ cd <project>
$ R
> packrat::init()
> packrat::restore()
# it failed on stringi for me for some reason
# Rcpp was probably not needed
> install.packages('Rcpp')
> install.packages('stringi')
> packrat::restore()
# R packages now locally installed to the project
> q()
```

I created a test json file
```json
{
    "messages": [
        {
            "timestamp": "20220504T000000Z",
            "author": {
                "name": "name1"
            },
            "content": "Message 1"
        },
        {
            "timestamp": "20220504T000030Z",
            "author": {
                "name": "name2"
            },
            "content": "Reply to message 1"
        },
        {
            "timestamp": "20220504T130000Z",
            "author": {
                "name": "name1"
            },
            "content": "message 2"
        }
    
    ]
}
```

 edited the import lines to

```r
chat_json <- read_json('./test.json')$messages
# in memory gunzip, highly recomended to compress large JSON logs
# read_json(...) == fromJson(..., simplifyVector = FALSE)
# but handles more than just a string filepath such as connections (R file objects)
#log_gzipped <- gzfile('./discord_chat_anonymized.json.gz', open = 'rb') # fromJSON needs binary
#chat_json <- fromJSON(log_gzipped, simplifyVector = FALSE)$messages
#close(log_gzipped)
```

and lastly removed the filtering by changing the tidying code to (`N < 0` rather than `N < 100`)

```r 
library(magrittr) # for %<>% (originator of %>%)
library(stringr)

chat %<>%
	.[!.[, .N, username][N < 0], on = 'username'] %>% # anti join
	.[, username := droplevels(username)] %>%
	.[, message := str_replace(message, '(https?\\S+)|(\\d{4,})', '')]
```

Then I ran
```bash
$ rm README.md
$ make README.md
```
and I got the Rmd built into the markdown file and also html. The html render looks good so I'm not sure what issue you are having.

I'm guessing that the tidy text library you are using changed the column names. You can use packrat to get the version I used or use `glimpse()` to take a look at the output right before the error to make sure `word1` and `word2` columns are present. Or the `bigram` column is present before `separate()`. If they are different change the names as appropriate.

**Comment by vrrdnt** [comment]
Thanks so much for the great write-up! I've never used R before, so I was kind of going into this blind.

Everything works now!

Out of curiosity - how might I filter out messages from bots? I know each message has an `isBot` flag, but don't know how I'd go about writing a filter for that. If you'd like me to make a separate issue for that or anything, let me know!

**Comment by BorisNikulin** [comment]
Look in the json for the isBots field. I think it's in the author object in each message. In the import stage, make a column for the isBot data like so

```r
chat <- data.table(
	timestamp = map_chr(chat_json, 'timestamp') %>% ymd_hms(),
	# Discord author JSON spec calls the field `username` not `name`
	username = map_chr(chat_json, c('author', 'name')) %>% as.factor(),
	message = map_chr(chat_json, 'content'),
	# maybe you'll need map_chr and parse manually, or maybe the field is absent so you'll maybe want to add .default=FALSE
	# see https://purrr.tidyverse.org/reference/map.html
	is_bot = map_lgl(chat, c('author', 'is_bot or whatever the field name is')
)
```

then you'll want to filter out rows in the dataframe where is_bot is false (or NA if .default=NA by default and it's an optional field) like so
```r
# same as chat <- chat[...]
chat  %<>% .[is_bot != FALSE,]
```

The dataframe library used in this project is data.table and you can checkout https://raw.githubusercontent.com/rstudio/cheatsheets/master/datatable.pdf for a reference. See also https://www.rstudio.com/resources/cheatsheets/ in general.

Note, I haven't tested any of the code so there are probably some issues.
